### ISSUE TITLE
Questions about the results

### ISSUE THREAD

**Issue by KangSH9776** [orobix/Visual-Feature-Attribution-Using-Wasserstein-GANs-Pytorch#2]
Hello! 

I got the following picture from the last epoch.

> epoch 1000 (fake image)
![fake_samples_19500](https://user-images.githubusercontent.com/29699676/43441620-faa20bee-948a-11e8-90da-e444b463860f.png)

> epoch 1000 (real Image + fake Image)
![sum_samples_19500](https://user-images.githubusercontent.com/29699676/43441656-111f89e6-948b-11e8-815b-96837fa1b89e.png)

I understand that only two square boxes of images in one of the 4 x 8 images add a generated image, but I do not like the image.

The sum_samples are like images that ignore the square and add a fake image to the real image.

> red : The part where the fake image is added to the real image without the area in the two squares boxes.
> blue :  two squares boxes.
![default](https://user-images.githubusercontent.com/29699676/43442135-9a9e357c-948c-11e8-8fd9-12e47d90d0a7.PNG)

I thought only the blue box added the fake image, but I think the red box added the fake image.

I want to know how to add images. 

Additionally, I would like to know how to train with ADNI data.

Thank you very much.
I look forward to hearing from you.

**Comment by dnlcrl** [comment]
For what concerns the train with ADNI data you can check the official repo https://github.com/baumgach/vagan-code/ and write a pr, as it hasn't been implemented yet.

About the images instead, I don't understand what are you asking for, (you also missed to post the original image), but that's how image are saved: https://github.com/orobix/Visual-Feature-Attribution-Using-Wasserstein-GANs-Pytorch/blob/9a99cc07f8e8602013aa417c9db400fe161660fb/src/train.py#L220-L230 

As you said, the sum samples are the fake images (anomaly map, or G(x)) + orig image (real samples, x), the discriminator distinguishes that sum from original, non-anomalous images (noise without white sqaures). One of the trouble you can get is that the fake image that get saved is the **inverted** map `plt.imsave(path, -img, cmap='gray') ` so what you see white is in reality black. But I can assure you there is not such thing as images added w/o certain areas.

Finally, I suggest you to pull/reclone the repo and re-run the code, these are the images I get after 600 epochs:

![real_samples](https://user-images.githubusercontent.com/1212655/43444602-7af95d56-94a4-11e8-9f27-87715c5939a0.png)
![fake_samples_00600](https://user-images.githubusercontent.com/1212655/43444655-9b568a56-94a4-11e8-8721-a13131881193.png)
![sum_samples_00600](https://user-images.githubusercontent.com/1212655/43444670-a43bab7e-94a4-11e8-9d7f-98a2e794bb30.png)

Thank you, I'm closing the issue, feel free to reopen it and/or add comments.
